config/routes.rb
BabyTribe::Application.routes.draw do

  root "home#index"
  
  devise_for :users, :skip => [:sessions]

  as :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    delete 'logout' => 'devise/sessions#destroy'
  end

  resources :users
  

  match '/help', to: "home#help", via: 'get'          #help_path
  get '/about', to: "home#about", as: 'about'        #about_path
  get '/calendar', to: "home#calendar", as: 'calendar'   #calendar_path

  

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  before_action :set_locale

  before_filter :authenticate_user!, except: [:index, :show, :calendar]

  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  def set_locale
    if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def help
  end

  def about
  end

  def calendar
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index

  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(title)
    base_title = "Thought Tribe"
    if title.empty?
      base_title
    else
      "#{base_title}|#{title}"
    end
  end

  def current_class(link)
    current_page?(link) ? "active" : ""
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def today
    Date.today
  end

  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar table table-bordered" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<% provide(:title,'About') %>
<h1>About</h1>

app/views/home/calendar.html.erb
<div id="icalendar" class="table-responsive">
<div id="month">
  <%= link_to raw("<span class='glyphicon glyphicon-chevron-left'></span>"), date: @date.prev_month %>
  <%= @date.strftime("%b %Y") %>
  <%= link_to raw("<span class='glyphicon glyphicon-chevron-right'></span>"), date: @date.next_month %>
</div>
<%= calendar @date do |date| %>
  <%= date.day -%>
<% end -%>
</div>

app/views/home/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>

app/views/home/index.html.erb
<div class="center jumbotron home_margin">
  <h1><%= t("body.content") %></h1>
  <h2>个人文字记录与分享平台，致力于构建高质量的思想交流平台。加入我们一起开启智慧的盛宴。</h2>
  <% if user_signed_in? %>
    <button class="btn btn-lg btn-success">Good Chosen!</button>
  <% else %>
    <%= link_to t("body.signup"), new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end -%>  
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>&copy; 2013 <a href="https://bitbucket.org/zhulinpinyu/babytribe/src"> Xtribe </a></small>
  <nav>
    <ul>
      <li><%= link_to "中文版",  controller: controller.controller_name, action: controller.action_name, locale: "zh_CN" -%></li>
      <li><%= link_to "English", controller: controller.controller_name, action: controller.action_name, locale: "en" -%></li>
      <li><%= link_to t('footer.help'), help_path -%></li>
      <li><%= link_to t('footer.about'), about_path -%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('header.title'), root_path, id: "logo", class: "navbar-brand", title: "掃特部落" %>
    </div>
    
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class=<%= current_class(root_path) %>><%= link_to t('header.community'), root_path %></li>
        <li class=<%= current_class(calendar_path) %>><%= link_to t('header.calendar'), calendar_path %></li>
        <li class=<%= current_class(users_path) %>><%= link_to "Users", users_path %></li>
        <li ><%= link_to "Notes", "#" %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-bell"></span>
                <span class="badge"></span>
              </a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.username %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('user.home'), current_user %></li>
                <li><%= link_to t('user.profile'), edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to t('header.logout'), logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
          <li class="pull-right">
          <%= link_to t('header.signin'), login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<h1><%= current_user.username %></h1>
<p>Find me in app/views/users/index.html.erb</p>